name: Backup DropDax Scraper

on:
  workflow_dispatch: # Allows you to run it manually with a button click + Allows cron-job.org to trigger this

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          CSV_FILENAME: dropcatch_results_backup.csv
        run: python scraper_headless.py

      - name: Safe Pull Logic
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # 1. Hide the new CSV temporarily
          git stash
          
          # 2. Update the code from GitHub
          git pull origin main --rebase
          
          # 3. Bring the CSV back (this might say 'No stash entries found' if it's a new file, so we allow failure)
          git stash pop || echo "Nothing to pop, proceeding..."

      - name: Commit and Push Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update daily auction results"
          file_pattern: "*.csv"
